# Generated by Django 3.2 on 2026-06-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='用户名')),
                ('question', models.TextField(verbose_name='提问内容')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='AI回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
