# Generated by Django 3.2 on 2024-04-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('brief', models.CharField(max_length=512, verbose_name='简介')),
                ('content', models.TextField(verbose_name='文章详情')),
                ('author', models.CharField(default='本站', max_length=55, verbose_name='作者')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('image', models.ImageField(default='upload/logo2_03.png', upload_to='upload', verbose_name='图片')),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=512, verbose_name='简介')),
                ('result', models.CharField(max_length=512, verbose_name='识别结果')),
                ('recognition_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('image', models.ImageField(default='upload/recognition/logo2_03.png', upload_to='upload/recognition', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=16, verbose_name='话题名称')),
                ('parent_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='用户昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=24, null=True, verbose_name='电话')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '已注销')], default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('parent_id', models.IntegerField(default=-1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article', verbose_name='所属文章')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.topic', verbose_name='所属话题'),
        ),
    ]
