# Generated by Django 3.2 on 2026-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
